image: docker:stable
options:
  docker: true
pipelines:
  default:
    - parallel:
      - step:
          script:
            - apk add --no-cache py-pip bash
            - pip install --no-cache-dir docker-compose
            - docker-compose run api mix test
      - step:
          script:
          - apk add --no-cache py-pip bash
          - pip install --no-cache-dir docker-compose
          - docker-compose run cli
