image: docker:stable
options:
  docker: true
pipelines:
  default:
    - parallel:
      - step:
          name: API Tests
          script:
          - apk add --no-cache py-pip bash
          - pip install --no-cache-dir docker-compose
          - docker-compose run api_test
      - step:
          name: Client Tests
          script:
          - apk add --no-cache py-pip bash
          - pip install --no-cache-dir docker-compose
          - docker-compose run cli
  branches:
    master:
    - parallel:
      - step:
          name: API Tests
          script:
          - apk add --no-cache py-pip bash
          - pip install --no-cache-dir docker-compose
          - docker-compose run api_test
      - step:
          name: Client Tests
          script:
          - apk add --no-cache py-pip bash
          - pip install --no-cache-dir docker-compose
          - docker-compose run cli
    - step:
        name: Push to Docker Hub
        script:
        - cd api
        - docker login -u $DOCKER_USERNAME -p "$DOCKER_PASSWORD"
        - docker build --target production -t pingaling/server:$MAJOR.$MINOR.$BITBUCKET_BUILD_NUMBER .
        - docker push pingaling/server:$MAJOR.$MINOR.$BITBUCKET_BUILD_NUMBER
