version: "3"
services:
  api_test:
    image: api
    build: api
    container_name: pingaling_api
    depends_on:
      - db
    ports:
      - 4000
    environment:
      - POSTGRES_HOST=db
      - MIX_ENV=test
      - PORT=4000
    command: mix test

  api_acceptance_tests:
    image: api_acceptance_tests
    build: api
    container_name: pingaling_api_acceptance_tests
    depends_on:
    - db
    ports:
    - 4000
    environment:
    - POSTGRES_HOST=db
    - MIX_ENV=dev
    - PORT=4000
    command: /bin/bash -c "mix ecto.reset && mix phx.server"

  db:
    image: postgres:10
    environment:
    - POSTGRES_PASSWORD=postgres

  cli:
    image: cli
    build: cli
    container_name: pingaling_cli
    depends_on:
      - api_acceptance_tests
    environment:
    - API_SERVER=http://api_acceptance_tests:4000/api
