version: "3.4"
services:
  api_test:
    image: api_tests
    build:
      context: .
      dockerfile: api/Dockerfile
      target: development
    container_name: pingaling_api
    depends_on:
      - db
    ports:
      - 4000
    environment:
      - POSTGRES_HOST=db
      - MIX_ENV=test
      - PORT=4000
    command: mix test

  api_acceptance_tests:
    image: api_acceptance_tests
    build:
      context: .
      dockerfile: api/Dockerfile
      target: development
    container_name: pingaling_api_acceptance_tests
    depends_on:
    - db_acceptance_tests
    ports:
    - 4000
    environment:
    - POSTGRES_HOST=db_acceptance_tests
    - MIX_ENV=dev
    - PORT=4000
    command: /bin/bash -c "mix ecto.reset && mix phx.server"

  db_acceptance_tests:
    image: postgres:10
    environment:
    - POSTGRES_PASSWORD=postgres

  db:
    image: postgres:10
    environment:
    - POSTGRES_PASSWORD=postgres

  cli:
    image: cli
    build:
      context: .
      dockerfile: cli/Dockerfile
    container_name: pingaling_cli
    depends_on:
      - api_acceptance_tests
    environment:
    - API_SERVER=http://api_acceptance_tests:4000/api
