version: "3"
services:
  api:
    image: api
    build: api
    container_name: pingaling_api
    depends_on:
      - db
    ports:
      - 4000
    environment:
      - POSTGRES_HOST=db

  db:
    image: postgres:10
    environment:
    - POSTGRES_PASSWORD=postgres

  cli:
    image: cli
    build: cli
    container_name: pingaling_cli
    depends_on:
      - api
    environment:
    - API_SERVER=http://api:4000/api
